### ISSUE TITLE
Make an option to whether clean up the folder after job run

### ISSUE THREAD

**Issue by huangp** [aeng/zanata-helper#22]
This will save time doing git clone

**Comment by aeng** [comment]
Work level or application level?

**Comment by huangp** [comment]
For the time being, maybe just application level

On Sun, Jan 17, 2016 at 12:18 PM, Alex Eng <notifications@github.com> wrote:

> Work level or application level?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aeng/zanata-helper/issues/22#issuecomment-172284820>.
>



-- 
Patrick Huang
Senior Software Engineer
Engineering - Internationalisation
Red Hat, Asia-Pacific Pty Ltd
Level 1, 193 North Quay
Brisbane 4000
Office: +61 7 3514 8278
Fax: +61 7 3514 8199
IRC: pahuang
github: github.com/huangp
Website: www.redhat.com
